package parser

import "fmt"

type CommentParser struct { ID int; Name string }

func (o *CommentParser) Function_1() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_2() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_3() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_4() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_5() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_6() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_7() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_8() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_9() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_10() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_11() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_12() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_13() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_14() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_15() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_16() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_17() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_18() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_19() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_20() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_21() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_22() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_23() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_24() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_25() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_26() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_27() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_28() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_29() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_30() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_31() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_32() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_33() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_34() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_35() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_36() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_37() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_38() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_39() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_40() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_41() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_42() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_43() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_44() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_45() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_46() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_47() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_48() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_49() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_50() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_51() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_52() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_53() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_54() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_55() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_56() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_57() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_58() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_59() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_60() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_61() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_62() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_63() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_64() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_65() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_66() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_67() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_68() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_69() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_70() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_71() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_72() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_73() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_74() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_75() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_76() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_77() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_78() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_79() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_80() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_81() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_82() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_83() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_84() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_85() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_86() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_87() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_88() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_89() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_90() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_91() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_92() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_93() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_94() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_95() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_96() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_97() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_98() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_99() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_100() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_101() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_102() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_103() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_104() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_105() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_106() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_107() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_108() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_109() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_110() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_111() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_112() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_113() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_114() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_115() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_116() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_117() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_118() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_119() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_120() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_121() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_122() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_123() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_124() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_125() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_126() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_127() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_128() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_129() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_130() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_131() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_132() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_133() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_134() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_135() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_136() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_137() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_138() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_139() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_140() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_141() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_142() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_143() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_144() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_145() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_146() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_147() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_148() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_149() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_150() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_151() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_152() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_153() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_154() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_155() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_156() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_157() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_158() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_159() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_160() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_161() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_162() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_163() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_164() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_165() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_166() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_167() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_168() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_169() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_170() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_171() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_172() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_173() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_174() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_175() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_176() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_177() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_178() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_179() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_180() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_181() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_182() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_183() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_184() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_185() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_186() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_187() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_188() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_189() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_190() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_191() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_192() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_193() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_194() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_195() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_196() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_197() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_198() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_199() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_200() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_201() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_202() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_203() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_204() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_205() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_206() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_207() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_208() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_209() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_210() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_211() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_212() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_213() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_214() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_215() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_216() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_217() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_218() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_219() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_220() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_221() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_222() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_223() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_224() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_225() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_226() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_227() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_228() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_229() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_230() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_231() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_232() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_233() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_234() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_235() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_236() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_237() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_238() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_239() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_240() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_241() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_242() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_243() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_244() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_245() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_246() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_247() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_248() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_249() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_250() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_251() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_252() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_253() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_254() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_255() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_256() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_257() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_258() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_259() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_260() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_261() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_262() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_263() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_264() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_265() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_266() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_267() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_268() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_269() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_270() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_271() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_272() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_273() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_274() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_275() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_276() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_277() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_278() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_279() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_280() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_281() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_282() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_283() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_284() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_285() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_286() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_287() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_288() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_289() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_290() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_291() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_292() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_293() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_294() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_295() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_296() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_297() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_298() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_299() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_300() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_301() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_302() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_303() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_304() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_305() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_306() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_307() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_308() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_309() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_310() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_311() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_312() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_313() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_314() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_315() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_316() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_317() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_318() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_319() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_320() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_321() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_322() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_323() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_324() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_325() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_326() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_327() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_328() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_329() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_330() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_331() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_332() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_333() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_334() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_335() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_336() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_337() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_338() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_339() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_340() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_341() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_342() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_343() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_344() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_345() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_346() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_347() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_348() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_349() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_350() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_351() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_352() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_353() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_354() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_355() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_356() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_357() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_358() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_359() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_360() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_361() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_362() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_363() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_364() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_365() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_366() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_367() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_368() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_369() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_370() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_371() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_372() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_373() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_374() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_375() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_376() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_377() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_378() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_379() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_380() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_381() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_382() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_383() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_384() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_385() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_386() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_387() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_388() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_389() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_390() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_391() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_392() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_393() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_394() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_395() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_396() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_397() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_398() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_399() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_400() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_401() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_402() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_403() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_404() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_405() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_406() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_407() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_408() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_409() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_410() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_411() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_412() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_413() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_414() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_415() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_416() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_417() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_418() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_419() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_420() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_421() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_422() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_423() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_424() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_425() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_426() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_427() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_428() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_429() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_430() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_431() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_432() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_433() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_434() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_435() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_436() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_437() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_438() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_439() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_440() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_441() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_442() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_443() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_444() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_445() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_446() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_447() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_448() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_449() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_450() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_451() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_452() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_453() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_454() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_455() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_456() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_457() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_458() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_459() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_460() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_461() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_462() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_463() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_464() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_465() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_466() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_467() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_468() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_469() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_470() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_471() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_472() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_473() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_474() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_475() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_476() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_477() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_478() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_479() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_480() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_481() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_482() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_483() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_484() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_485() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_486() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_487() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_488() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_489() string { return fmt.Sprintf("%d", o.ID) }
func (o *CommentParser) Function_490() string { return fmt.Sprintf("%d", o.ID) }
