package codebasesurvey

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	surveyDirName      = "codebase_semantic"
	manifestFileName   = "manifest.json"
	overviewFileName   = "overview.md"
	shardInputsDirName = "inputs"
	shardGraphsDirName = "graphs"
)

type Manifest struct {
	RepoRoot       string          `json:"repo_root"`
	ScopePath      string          `json:"scope_path"`
	HeadCommit     string          `json:"head_commit,omitempty"`
	IndexEpoch     int64           `json:"index_epoch"`
	GeneratedAt    time.Time       `json:"generated_at"`
	Status         string          `json:"status"`
	AgentCount     int             `json:"agent_count"`
	TotalFiles     int             `json:"total_files"`
	OverviewPath   string          `json:"overview_path,omitempty"`
	Overview       []string        `json:"overview,omitempty"`
	CriticalFiles  []string        `json:"critical_files,omitempty"`
	ShardArtifacts []ShardArtifact `json:"shard_artifacts,omitempty"`
}

type ShardInput struct {
	ShardID        string         `json:"shard_id"`
	Label          string         `json:"label"`
	RepoRoot       string         `json:"repo_root"`
	ScopePath      string         `json:"scope_path"`
	HeadCommit     string         `json:"head_commit,omitempty"`
	IndexEpoch     int64          `json:"index_epoch"`
	AssignedFiles  []string       `json:"assigned_files"`
	TopDirectories []string       `json:"top_directories,omitempty"`
	CriticalFiles  []string       `json:"critical_files,omitempty"`
	LanguageCounts map[string]int `json:"language_counts,omitempty"`
}

type ShardArtifact struct {
	ShardID        string   `json:"shard_id"`
	Label          string   `json:"label"`
	AgentID        string   `json:"agent_id,omitempty"`
	WorkItemID     string   `json:"work_item_id,omitempty"`
	Status         string   `json:"status"`
	FileCount      int      `json:"file_count"`
	TopDirectories []string `json:"top_directories,omitempty"`
	CriticalFiles  []string `json:"critical_files,omitempty"`
	Summary        string   `json:"summary,omitempty"`
	ArtifactPath   string   `json:"artifact_path,omitempty"`
	Error          string   `json:"error,omitempty"`
}

func Dir(dataDir string) string {
	return filepath.Join(strings.TrimSpace(dataDir), "memory", surveyDirName)
}

func ManifestPath(dataDir string) string {
	return filepath.Join(Dir(dataDir), manifestFileName)
}

func OverviewPath(dataDir string) string {
	return filepath.Join(Dir(dataDir), overviewFileName)
}

func ShardInputPath(dataDir, shardID string) string {
	return filepath.Join(Dir(dataDir), shardInputsDirName, shardID+".json")
}

func ShardGraphPath(dataDir, shardID string) string {
	return filepath.Join(Dir(dataDir), shardGraphsDirName, shardID+".md")
}

func EnsureLayout(dataDir string) error {
	for _, path := range []string{
		Dir(dataDir),
		filepath.Join(Dir(dataDir), shardInputsDirName),
		filepath.Join(Dir(dataDir), shardGraphsDirName),
	} {
		if err := os.MkdirAll(path, 0o755); err != nil {
			return err
		}
	}
	return nil
}

func WriteShardInput(dataDir string, input ShardInput) (string, error) {
	if err := EnsureLayout(dataDir); err != nil {
		return "", err
	}
	path := ShardInputPath(dataDir, input.ShardID)
	payload, err := json.MarshalIndent(input, "", "  ")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, append(payload, '\n'), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func WriteManifest(dataDir string, manifest Manifest) error {
	if err := EnsureLayout(dataDir); err != nil {
		return err
	}
	if manifest.OverviewPath == "" {
		manifest.OverviewPath = OverviewPath(dataDir)
	}
	payload, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(ManifestPath(dataDir), append(payload, '\n'), 0o644); err != nil {
		return err
	}
	overview := RenderOverview(manifest)
	if overview != "" && shouldWriteOverview(manifest.OverviewPath) {
		if err := os.WriteFile(manifest.OverviewPath, []byte(overview), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func ReadManifest(dataDir string) (Manifest, bool, error) {
	data, err := os.ReadFile(ManifestPath(dataDir))
	if err != nil {
		if os.IsNotExist(err) {
			return Manifest{}, false, nil
		}
		return Manifest{}, false, err
	}
	var manifest Manifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return Manifest{}, false, err
	}
	return manifest, true, nil
}

func RenderOverview(manifest Manifest) string {
	var lines []string
	lines = append(lines,
		"# AI Codebase Graph",
		"",
		"AI-authored durable codebase survey generated by Sapphire sub-agents.",
		"",
		fmt.Sprintf("- status: %s", strings.TrimSpace(manifest.Status)),
		fmt.Sprintf("- generated_at: %s", manifest.GeneratedAt.UTC().Format(time.RFC3339)),
		fmt.Sprintf("- agent_count: %d", manifest.AgentCount),
		fmt.Sprintf("- total_files: %d", manifest.TotalFiles),
	)
	if manifest.RepoRoot != "" {
		lines = append(lines, fmt.Sprintf("- repo_root: %s", manifest.RepoRoot))
	}
	if manifest.ScopePath != "" {
		lines = append(lines, fmt.Sprintf("- scope_path: %s", manifest.ScopePath))
	}
	if manifest.HeadCommit != "" {
		lines = append(lines, fmt.Sprintf("- head_commit: %s", manifest.HeadCommit))
	}
	if manifest.IndexEpoch != 0 {
		lines = append(lines, fmt.Sprintf("- index_epoch: %d", manifest.IndexEpoch))
	}

	if len(manifest.Overview) > 0 {
		lines = append(lines, "", "## Architecture Overview")
		for _, item := range manifest.Overview {
			item = strings.TrimSpace(item)
			if item == "" {
				continue
			}
			if strings.HasPrefix(item, "- ") {
				lines = append(lines, item)
				continue
			}
			lines = append(lines, "- "+item)
		}
	}

	if len(manifest.CriticalFiles) > 0 {
		lines = append(lines, "", "## Critical Files")
		for _, path := range manifest.CriticalFiles {
			path = strings.TrimSpace(path)
			if path != "" {
				lines = append(lines, "- "+path)
			}
		}
	}

	if len(manifest.ShardArtifacts) > 0 {
		lines = append(lines, "", "## Shards")
		for _, shard := range manifest.ShardArtifacts {
			line := fmt.Sprintf("- %s [%s] files=%d", firstNonEmpty(shard.Label, shard.ShardID), strings.TrimSpace(shard.Status), shard.FileCount)
			if shard.Summary != "" {
				line += " | " + strings.TrimSpace(shard.Summary)
			}
			if shard.ArtifactPath != "" {
				line += " | artifact=" + shard.ArtifactPath
			}
			if shard.Error != "" {
				line += " | error=" + strings.TrimSpace(shard.Error)
			}
			lines = append(lines, line)
		}
	}

	return strings.TrimSpace(strings.Join(lines, "\n")) + "\n"
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

func shouldWriteOverview(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return true
	}
	return info.Size() == 0
}
