package utils

import "fmt"

type PathUtils struct { ID int; Name string }

func (o *PathUtils) Function_1() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_2() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_3() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_4() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_5() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_6() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_7() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_8() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_9() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_10() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_11() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_12() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_13() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_14() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_15() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_16() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_17() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_18() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_19() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_20() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_21() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_22() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_23() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_24() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_25() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_26() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_27() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_28() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_29() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_30() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_31() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_32() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_33() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_34() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_35() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_36() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_37() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_38() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_39() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_40() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_41() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_42() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_43() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_44() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_45() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_46() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_47() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_48() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_49() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_50() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_51() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_52() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_53() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_54() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_55() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_56() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_57() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_58() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_59() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_60() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_61() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_62() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_63() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_64() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_65() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_66() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_67() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_68() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_69() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_70() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_71() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_72() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_73() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_74() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_75() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_76() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_77() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_78() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_79() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_80() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_81() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_82() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_83() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_84() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_85() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_86() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_87() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_88() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_89() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_90() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_91() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_92() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_93() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_94() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_95() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_96() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_97() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_98() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_99() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_100() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_101() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_102() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_103() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_104() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_105() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_106() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_107() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_108() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_109() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_110() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_111() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_112() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_113() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_114() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_115() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_116() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_117() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_118() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_119() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_120() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_121() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_122() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_123() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_124() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_125() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_126() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_127() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_128() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_129() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_130() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_131() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_132() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_133() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_134() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_135() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_136() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_137() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_138() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_139() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_140() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_141() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_142() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_143() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_144() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_145() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_146() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_147() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_148() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_149() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_150() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_151() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_152() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_153() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_154() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_155() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_156() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_157() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_158() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_159() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_160() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_161() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_162() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_163() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_164() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_165() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_166() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_167() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_168() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_169() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_170() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_171() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_172() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_173() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_174() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_175() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_176() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_177() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_178() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_179() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_180() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_181() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_182() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_183() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_184() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_185() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_186() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_187() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_188() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_189() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_190() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_191() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_192() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_193() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_194() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_195() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_196() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_197() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_198() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_199() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_200() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_201() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_202() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_203() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_204() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_205() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_206() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_207() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_208() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_209() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_210() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_211() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_212() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_213() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_214() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_215() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_216() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_217() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_218() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_219() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_220() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_221() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_222() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_223() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_224() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_225() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_226() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_227() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_228() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_229() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_230() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_231() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_232() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_233() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_234() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_235() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_236() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_237() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_238() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_239() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_240() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_241() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_242() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_243() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_244() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_245() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_246() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_247() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_248() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_249() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_250() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_251() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_252() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_253() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_254() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_255() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_256() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_257() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_258() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_259() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_260() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_261() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_262() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_263() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_264() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_265() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_266() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_267() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_268() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_269() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_270() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_271() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_272() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_273() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_274() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_275() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_276() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_277() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_278() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_279() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_280() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_281() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_282() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_283() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_284() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_285() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_286() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_287() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_288() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_289() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_290() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_291() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_292() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_293() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_294() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_295() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_296() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_297() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_298() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_299() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_300() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_301() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_302() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_303() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_304() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_305() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_306() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_307() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_308() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_309() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_310() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_311() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_312() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_313() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_314() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_315() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_316() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_317() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_318() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_319() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_320() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_321() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_322() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_323() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_324() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_325() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_326() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_327() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_328() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_329() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_330() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_331() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_332() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_333() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_334() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_335() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_336() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_337() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_338() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_339() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_340() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_341() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_342() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_343() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_344() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_345() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_346() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_347() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_348() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_349() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_350() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_351() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_352() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_353() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_354() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_355() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_356() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_357() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_358() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_359() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_360() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_361() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_362() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_363() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_364() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_365() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_366() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_367() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_368() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_369() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_370() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_371() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_372() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_373() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_374() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_375() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_376() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_377() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_378() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_379() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_380() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_381() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_382() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_383() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_384() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_385() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_386() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_387() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_388() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_389() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_390() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_391() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_392() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_393() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_394() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_395() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_396() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_397() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_398() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_399() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_400() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_401() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_402() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_403() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_404() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_405() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_406() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_407() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_408() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_409() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_410() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_411() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_412() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_413() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_414() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_415() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_416() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_417() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_418() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_419() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_420() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_421() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_422() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_423() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_424() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_425() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_426() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_427() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_428() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_429() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_430() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_431() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_432() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_433() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_434() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_435() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_436() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_437() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_438() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_439() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_440() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_441() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_442() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_443() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_444() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_445() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_446() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_447() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_448() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_449() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_450() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_451() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_452() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_453() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_454() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_455() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_456() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_457() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_458() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_459() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_460() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_461() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_462() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_463() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_464() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_465() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_466() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_467() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_468() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_469() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_470() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_471() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_472() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_473() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_474() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_475() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_476() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_477() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_478() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_479() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_480() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_481() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_482() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_483() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_484() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_485() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_486() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_487() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_488() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_489() string { return fmt.Sprintf("%d", o.ID) }
func (o *PathUtils) Function_490() string { return fmt.Sprintf("%d", o.ID) }
