package utils

import "fmt"

type StringUtils struct { ID int; Name string }

func (o *StringUtils) Function_1() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_2() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_3() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_4() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_5() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_6() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_7() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_8() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_9() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_10() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_11() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_12() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_13() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_14() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_15() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_16() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_17() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_18() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_19() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_20() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_21() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_22() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_23() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_24() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_25() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_26() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_27() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_28() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_29() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_30() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_31() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_32() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_33() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_34() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_35() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_36() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_37() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_38() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_39() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_40() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_41() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_42() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_43() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_44() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_45() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_46() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_47() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_48() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_49() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_50() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_51() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_52() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_53() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_54() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_55() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_56() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_57() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_58() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_59() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_60() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_61() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_62() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_63() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_64() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_65() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_66() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_67() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_68() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_69() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_70() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_71() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_72() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_73() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_74() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_75() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_76() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_77() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_78() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_79() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_80() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_81() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_82() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_83() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_84() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_85() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_86() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_87() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_88() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_89() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_90() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_91() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_92() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_93() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_94() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_95() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_96() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_97() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_98() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_99() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_100() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_101() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_102() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_103() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_104() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_105() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_106() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_107() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_108() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_109() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_110() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_111() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_112() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_113() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_114() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_115() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_116() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_117() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_118() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_119() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_120() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_121() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_122() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_123() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_124() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_125() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_126() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_127() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_128() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_129() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_130() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_131() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_132() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_133() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_134() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_135() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_136() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_137() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_138() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_139() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_140() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_141() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_142() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_143() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_144() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_145() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_146() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_147() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_148() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_149() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_150() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_151() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_152() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_153() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_154() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_155() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_156() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_157() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_158() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_159() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_160() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_161() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_162() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_163() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_164() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_165() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_166() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_167() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_168() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_169() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_170() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_171() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_172() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_173() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_174() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_175() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_176() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_177() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_178() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_179() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_180() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_181() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_182() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_183() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_184() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_185() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_186() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_187() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_188() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_189() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_190() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_191() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_192() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_193() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_194() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_195() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_196() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_197() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_198() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_199() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_200() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_201() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_202() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_203() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_204() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_205() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_206() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_207() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_208() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_209() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_210() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_211() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_212() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_213() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_214() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_215() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_216() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_217() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_218() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_219() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_220() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_221() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_222() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_223() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_224() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_225() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_226() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_227() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_228() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_229() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_230() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_231() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_232() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_233() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_234() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_235() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_236() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_237() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_238() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_239() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_240() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_241() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_242() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_243() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_244() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_245() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_246() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_247() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_248() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_249() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_250() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_251() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_252() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_253() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_254() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_255() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_256() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_257() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_258() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_259() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_260() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_261() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_262() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_263() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_264() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_265() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_266() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_267() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_268() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_269() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_270() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_271() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_272() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_273() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_274() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_275() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_276() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_277() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_278() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_279() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_280() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_281() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_282() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_283() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_284() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_285() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_286() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_287() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_288() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_289() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_290() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_291() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_292() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_293() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_294() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_295() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_296() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_297() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_298() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_299() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_300() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_301() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_302() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_303() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_304() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_305() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_306() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_307() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_308() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_309() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_310() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_311() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_312() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_313() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_314() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_315() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_316() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_317() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_318() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_319() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_320() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_321() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_322() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_323() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_324() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_325() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_326() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_327() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_328() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_329() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_330() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_331() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_332() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_333() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_334() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_335() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_336() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_337() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_338() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_339() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_340() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_341() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_342() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_343() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_344() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_345() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_346() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_347() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_348() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_349() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_350() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_351() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_352() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_353() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_354() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_355() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_356() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_357() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_358() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_359() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_360() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_361() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_362() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_363() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_364() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_365() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_366() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_367() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_368() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_369() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_370() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_371() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_372() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_373() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_374() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_375() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_376() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_377() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_378() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_379() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_380() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_381() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_382() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_383() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_384() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_385() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_386() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_387() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_388() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_389() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_390() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_391() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_392() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_393() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_394() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_395() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_396() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_397() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_398() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_399() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_400() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_401() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_402() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_403() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_404() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_405() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_406() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_407() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_408() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_409() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_410() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_411() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_412() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_413() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_414() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_415() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_416() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_417() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_418() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_419() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_420() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_421() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_422() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_423() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_424() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_425() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_426() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_427() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_428() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_429() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_430() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_431() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_432() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_433() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_434() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_435() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_436() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_437() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_438() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_439() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_440() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_441() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_442() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_443() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_444() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_445() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_446() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_447() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_448() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_449() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_450() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_451() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_452() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_453() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_454() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_455() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_456() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_457() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_458() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_459() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_460() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_461() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_462() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_463() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_464() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_465() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_466() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_467() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_468() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_469() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_470() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_471() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_472() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_473() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_474() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_475() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_476() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_477() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_478() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_479() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_480() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_481() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_482() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_483() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_484() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_485() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_486() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_487() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_488() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_489() string { return fmt.Sprintf("%d", o.ID) }
func (o *StringUtils) Function_490() string { return fmt.Sprintf("%d", o.ID) }
