package scanner

import "fmt"

type DirWalker struct { ID int; Name string }

func (o *DirWalker) Function_1() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_2() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_3() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_4() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_5() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_6() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_7() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_8() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_9() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_10() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_11() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_12() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_13() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_14() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_15() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_16() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_17() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_18() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_19() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_20() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_21() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_22() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_23() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_24() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_25() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_26() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_27() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_28() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_29() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_30() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_31() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_32() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_33() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_34() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_35() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_36() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_37() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_38() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_39() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_40() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_41() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_42() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_43() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_44() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_45() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_46() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_47() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_48() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_49() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_50() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_51() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_52() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_53() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_54() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_55() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_56() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_57() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_58() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_59() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_60() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_61() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_62() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_63() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_64() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_65() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_66() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_67() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_68() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_69() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_70() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_71() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_72() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_73() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_74() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_75() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_76() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_77() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_78() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_79() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_80() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_81() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_82() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_83() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_84() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_85() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_86() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_87() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_88() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_89() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_90() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_91() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_92() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_93() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_94() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_95() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_96() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_97() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_98() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_99() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_100() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_101() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_102() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_103() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_104() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_105() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_106() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_107() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_108() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_109() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_110() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_111() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_112() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_113() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_114() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_115() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_116() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_117() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_118() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_119() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_120() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_121() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_122() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_123() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_124() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_125() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_126() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_127() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_128() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_129() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_130() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_131() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_132() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_133() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_134() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_135() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_136() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_137() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_138() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_139() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_140() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_141() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_142() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_143() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_144() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_145() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_146() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_147() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_148() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_149() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_150() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_151() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_152() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_153() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_154() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_155() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_156() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_157() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_158() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_159() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_160() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_161() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_162() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_163() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_164() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_165() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_166() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_167() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_168() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_169() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_170() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_171() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_172() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_173() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_174() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_175() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_176() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_177() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_178() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_179() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_180() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_181() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_182() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_183() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_184() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_185() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_186() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_187() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_188() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_189() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_190() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_191() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_192() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_193() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_194() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_195() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_196() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_197() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_198() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_199() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_200() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_201() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_202() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_203() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_204() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_205() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_206() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_207() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_208() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_209() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_210() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_211() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_212() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_213() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_214() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_215() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_216() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_217() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_218() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_219() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_220() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_221() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_222() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_223() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_224() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_225() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_226() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_227() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_228() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_229() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_230() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_231() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_232() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_233() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_234() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_235() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_236() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_237() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_238() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_239() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_240() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_241() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_242() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_243() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_244() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_245() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_246() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_247() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_248() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_249() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_250() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_251() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_252() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_253() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_254() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_255() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_256() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_257() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_258() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_259() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_260() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_261() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_262() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_263() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_264() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_265() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_266() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_267() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_268() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_269() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_270() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_271() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_272() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_273() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_274() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_275() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_276() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_277() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_278() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_279() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_280() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_281() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_282() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_283() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_284() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_285() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_286() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_287() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_288() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_289() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_290() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_291() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_292() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_293() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_294() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_295() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_296() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_297() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_298() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_299() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_300() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_301() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_302() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_303() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_304() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_305() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_306() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_307() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_308() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_309() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_310() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_311() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_312() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_313() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_314() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_315() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_316() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_317() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_318() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_319() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_320() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_321() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_322() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_323() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_324() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_325() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_326() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_327() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_328() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_329() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_330() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_331() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_332() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_333() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_334() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_335() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_336() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_337() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_338() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_339() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_340() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_341() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_342() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_343() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_344() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_345() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_346() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_347() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_348() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_349() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_350() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_351() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_352() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_353() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_354() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_355() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_356() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_357() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_358() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_359() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_360() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_361() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_362() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_363() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_364() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_365() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_366() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_367() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_368() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_369() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_370() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_371() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_372() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_373() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_374() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_375() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_376() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_377() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_378() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_379() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_380() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_381() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_382() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_383() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_384() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_385() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_386() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_387() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_388() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_389() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_390() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_391() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_392() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_393() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_394() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_395() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_396() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_397() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_398() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_399() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_400() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_401() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_402() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_403() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_404() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_405() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_406() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_407() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_408() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_409() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_410() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_411() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_412() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_413() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_414() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_415() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_416() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_417() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_418() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_419() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_420() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_421() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_422() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_423() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_424() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_425() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_426() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_427() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_428() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_429() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_430() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_431() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_432() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_433() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_434() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_435() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_436() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_437() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_438() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_439() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_440() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_441() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_442() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_443() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_444() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_445() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_446() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_447() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_448() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_449() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_450() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_451() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_452() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_453() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_454() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_455() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_456() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_457() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_458() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_459() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_460() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_461() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_462() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_463() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_464() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_465() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_466() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_467() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_468() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_469() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_470() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_471() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_472() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_473() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_474() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_475() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_476() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_477() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_478() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_479() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_480() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_481() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_482() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_483() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_484() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_485() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_486() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_487() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_488() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_489() string { return fmt.Sprintf("%d", o.ID) }
func (o *DirWalker) Function_490() string { return fmt.Sprintf("%d", o.ID) }
