// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: long_horizon.sql

package db

import (
	"context"
)

const getLongHorizonRun = `-- name: GetLongHorizonRun :one
SELECT session_id, status, runbook_md, frozen_spec_md, audit_log, activated, updated_at, created_at
FROM long_horizon_runs
WHERE session_id = ?
`

func (q *Queries) GetLongHorizonRun(ctx context.Context, sessionID string) (LongHorizonRun, error) {
	row := q.queryRow(ctx, q.getLongHorizonRunStmt, getLongHorizonRun, sessionID)
	var i LongHorizonRun
	err := row.Scan(
		&i.SessionID,
		&i.Status,
		&i.RunbookMd,
		&i.FrozenSpecMd,
		&i.AuditLog,
		&i.Activated,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLongHorizonMilestones = `-- name: ListLongHorizonMilestones :many
SELECT session_id, milestone_id, position, name, condition, status, updated_at, created_at
FROM long_horizon_milestones
WHERE session_id = ?
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListLongHorizonMilestones(ctx context.Context, sessionID string) ([]LongHorizonMilestone, error) {
	rows, err := q.query(ctx, q.listLongHorizonMilestonesStmt, listLongHorizonMilestones, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LongHorizonMilestone{}
	for rows.Next() {
		var i LongHorizonMilestone
		if err := rows.Scan(
			&i.SessionID,
			&i.MilestoneID,
			&i.Position,
			&i.Name,
			&i.Condition,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceLongHorizonMilestones = `-- name: ReplaceLongHorizonMilestones :exec
DELETE FROM long_horizon_milestones
WHERE session_id = ?
`

func (q *Queries) ReplaceLongHorizonMilestones(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.replaceLongHorizonMilestonesStmt, replaceLongHorizonMilestones, sessionID)
	return err
}

const upsertLongHorizonMilestone = `-- name: UpsertLongHorizonMilestone :exec
INSERT INTO long_horizon_milestones (
    session_id,
    milestone_id,
    position,
    name,
    condition,
    status,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    unixepoch(),
    unixepoch()
)
ON CONFLICT(session_id, milestone_id) DO UPDATE SET
    position = excluded.position,
    name = excluded.name,
    condition = excluded.condition,
    status = excluded.status,
    updated_at = unixepoch()
`

type UpsertLongHorizonMilestoneParams struct {
	SessionID   string `json:"session_id"`
	MilestoneID string `json:"milestone_id"`
	Position    int64  `json:"position"`
	Name        string `json:"name"`
	Condition   string `json:"condition"`
	Status      string `json:"status"`
}

func (q *Queries) UpsertLongHorizonMilestone(ctx context.Context, arg UpsertLongHorizonMilestoneParams) error {
	_, err := q.exec(ctx, q.upsertLongHorizonMilestoneStmt, upsertLongHorizonMilestone,
		arg.SessionID,
		arg.MilestoneID,
		arg.Position,
		arg.Name,
		arg.Condition,
		arg.Status,
	)
	return err
}

const upsertLongHorizonRun = `-- name: UpsertLongHorizonRun :one
INSERT INTO long_horizon_runs (
    session_id,
    status,
    runbook_md,
    frozen_spec_md,
    audit_log,
    activated,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    unixepoch(),
    unixepoch()
)
ON CONFLICT(session_id) DO UPDATE SET
    status = excluded.status,
    runbook_md = excluded.runbook_md,
    frozen_spec_md = excluded.frozen_spec_md,
    audit_log = excluded.audit_log,
    activated = excluded.activated,
    updated_at = unixepoch()
RETURNING session_id, status, runbook_md, frozen_spec_md, audit_log, activated, updated_at, created_at
`

type UpsertLongHorizonRunParams struct {
	SessionID    string `json:"session_id"`
	Status       string `json:"status"`
	RunbookMd    string `json:"runbook_md"`
	FrozenSpecMd string `json:"frozen_spec_md"`
	AuditLog     string `json:"audit_log"`
	Activated    int64  `json:"activated"`
}

func (q *Queries) UpsertLongHorizonRun(ctx context.Context, arg UpsertLongHorizonRunParams) (LongHorizonRun, error) {
	row := q.queryRow(ctx, q.upsertLongHorizonRunStmt, upsertLongHorizonRun,
		arg.SessionID,
		arg.Status,
		arg.RunbookMd,
		arg.FrozenSpecMd,
		arg.AuditLog,
		arg.Activated,
	)
	var i LongHorizonRun
	err := row.Scan(
		&i.SessionID,
		&i.Status,
		&i.RunbookMd,
		&i.FrozenSpecMd,
		&i.AuditLog,
		&i.Activated,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
