// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package db

import (
	"context"
	"database/sql"
)

const claimGlobalPhase2Job = `-- name: ClaimGlobalPhase2Job :one
UPDATE memory_phase2_jobs
SET status = 'claimed',
    claim_token = ?1,
    lease_expires_at = ?2,
    dirty = 0,
    updated_at = ?3
WHERE singleton_id IN (
    SELECT singleton_id
    FROM memory_phase2_jobs
    WHERE singleton_id = 1
      AND input_watermark > last_output_watermark
      AND (retry_after = 0 OR retry_after <= ?3)
      AND (lease_expires_at IS NULL OR lease_expires_at <= ?3)
)
RETURNING singleton_id, dirty, status, claim_token, lease_expires_at, retry_after, input_watermark, last_output_watermark, last_error, updated_at, created_at
`

type ClaimGlobalPhase2JobParams struct {
	ClaimToken     sql.NullString `json:"claim_token"`
	LeaseExpiresAt sql.NullInt64  `json:"lease_expires_at"`
	Now            int64          `json:"now"`
}

func (q *Queries) ClaimGlobalPhase2Job(ctx context.Context, arg ClaimGlobalPhase2JobParams) (MemoryPhase2Job, error) {
	row := q.queryRow(ctx, q.claimGlobalPhase2JobStmt, claimGlobalPhase2Job, arg.ClaimToken, arg.LeaseExpiresAt, arg.Now)
	var i MemoryPhase2Job
	err := row.Scan(
		&i.SingletonID,
		&i.Dirty,
		&i.Status,
		&i.ClaimToken,
		&i.LeaseExpiresAt,
		&i.RetryAfter,
		&i.InputWatermark,
		&i.LastOutputWatermark,
		&i.LastError,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const claimStage1JobsForStartup = `-- name: ClaimStage1JobsForStartup :many
UPDATE memory_stage1_jobs
SET status = 'claimed',
    claimed_by = ?1,
    lease_expires_at = ?2,
    updated_at = ?3
WHERE session_id IN (
    SELECT session_id
    FROM memory_stage1_jobs
    WHERE status IN ('eligible', 'failed')
      AND (retry_after = 0 OR retry_after <= ?3)
      AND (lease_expires_at IS NULL OR lease_expires_at <= ?3)
    ORDER BY updated_at ASC, created_at ASC
    LIMIT ?4
)
RETURNING session_id, rollout_path, cwd, status, claimed_by, lease_expires_at, retry_after, updated_at, created_at
`

type ClaimStage1JobsForStartupParams struct {
	ClaimedBy      sql.NullString `json:"claimed_by"`
	LeaseExpiresAt sql.NullInt64  `json:"lease_expires_at"`
	Now            int64          `json:"now"`
	LimitCount     int64          `json:"limit_count"`
}

func (q *Queries) ClaimStage1JobsForStartup(ctx context.Context, arg ClaimStage1JobsForStartupParams) ([]MemoryStage1Job, error) {
	rows, err := q.query(ctx, q.claimStage1JobsForStartupStmt, claimStage1JobsForStartup,
		arg.ClaimedBy,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryStage1Job{}
	for rows.Next() {
		var i MemoryStage1Job
		if err := rows.Scan(
			&i.SessionID,
			&i.RolloutPath,
			&i.Cwd,
			&i.Status,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.RetryAfter,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearPhase2BaselineSelection = `-- name: ClearPhase2BaselineSelection :exec
UPDATE memory_stage1_outputs
SET selected_for_phase2 = 0,
    selected_for_phase2_source_updated_at = NULL
WHERE selected_for_phase2 = 1
`

func (q *Queries) ClearPhase2BaselineSelection(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearPhase2BaselineSelectionStmt, clearPhase2BaselineSelection)
	return err
}

const deleteStage1OutputBySessionID = `-- name: DeleteStage1OutputBySessionID :execrows
DELETE FROM memory_stage1_outputs
WHERE session_id = ?
`

func (q *Queries) DeleteStage1OutputBySessionID(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.exec(ctx, q.deleteStage1OutputBySessionIDStmt, deleteStage1OutputBySessionID, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureGlobalPhase2Job = `-- name: EnsureGlobalPhase2Job :exec
INSERT INTO memory_phase2_jobs (
    singleton_id,
    dirty,
    status,
    updated_at,
    created_at
) VALUES (
    1,
    1,
    'idle',
    unixepoch(),
    unixepoch()
)
ON CONFLICT(singleton_id) DO NOTHING
`

func (q *Queries) EnsureGlobalPhase2Job(ctx context.Context) error {
	_, err := q.exec(ctx, q.ensureGlobalPhase2JobStmt, ensureGlobalPhase2Job)
	return err
}

const ensureStage1JobForSession = `-- name: EnsureStage1JobForSession :exec
INSERT INTO memory_stage1_jobs (
    session_id,
    rollout_path,
    cwd,
    status,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    'eligible',
    unixepoch(),
    unixepoch()
)
ON CONFLICT(session_id) DO UPDATE SET
    rollout_path = excluded.rollout_path,
    cwd = excluded.cwd,
    updated_at = unixepoch()
`

type EnsureStage1JobForSessionParams struct {
	SessionID   string `json:"session_id"`
	RolloutPath string `json:"rollout_path"`
	Cwd         string `json:"cwd"`
}

func (q *Queries) EnsureStage1JobForSession(ctx context.Context, arg EnsureStage1JobForSessionParams) error {
	_, err := q.exec(ctx, q.ensureStage1JobForSessionStmt, ensureStage1JobForSession, arg.SessionID, arg.RolloutPath, arg.Cwd)
	return err
}

const failGlobalPhase2Job = `-- name: FailGlobalPhase2Job :execrows
UPDATE memory_phase2_jobs
SET status = 'failed',
    claim_token = NULL,
    lease_expires_at = NULL,
    retry_after = ?,
    last_error = ?,
    updated_at = unixepoch()
WHERE singleton_id = 1
  AND claim_token = ?
`

type FailGlobalPhase2JobParams struct {
	RetryAfter int64          `json:"retry_after"`
	LastError  string         `json:"last_error"`
	ClaimToken sql.NullString `json:"claim_token"`
}

func (q *Queries) FailGlobalPhase2Job(ctx context.Context, arg FailGlobalPhase2JobParams) (int64, error) {
	result, err := q.exec(ctx, q.failGlobalPhase2JobStmt, failGlobalPhase2Job, arg.RetryAfter, arg.LastError, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemoryRegistryMaterialization = `-- name: GetMemoryRegistryMaterialization :one
SELECT path, kind, content, session_id, updated_at, created_at
FROM memory_materializations
WHERE kind = 'registry'
LIMIT 1
`

func (q *Queries) GetMemoryRegistryMaterialization(ctx context.Context) (MemoryMaterialization, error) {
	row := q.queryRow(ctx, q.getMemoryRegistryMaterializationStmt, getMemoryRegistryMaterialization)
	var i MemoryMaterialization
	err := row.Scan(
		&i.Path,
		&i.Kind,
		&i.Content,
		&i.SessionID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMemorySummaryMaterialization = `-- name: GetMemorySummaryMaterialization :one
SELECT path, kind, content, session_id, updated_at, created_at
FROM memory_materializations
WHERE kind = 'summary'
LIMIT 1
`

func (q *Queries) GetMemorySummaryMaterialization(ctx context.Context) (MemoryMaterialization, error) {
	row := q.queryRow(ctx, q.getMemorySummaryMaterializationStmt, getMemorySummaryMaterialization)
	var i MemoryMaterialization
	err := row.Scan(
		&i.Path,
		&i.Kind,
		&i.Content,
		&i.SessionID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPhase2InputSelection = `-- name: GetPhase2InputSelection :many
SELECT session_id, source_updated_at, raw_memory, rollout_summary, rollout_slug, rollout_summary_file, usage_count, last_usage, selected_for_phase2, selected_for_phase2_source_updated_at, generated_at, used_at, updated_at, created_at
FROM memory_stage1_outputs
WHERE updated_at > ?
ORDER BY updated_at DESC
`

type GetPhase2InputSelectionRow struct {
	SessionID                        string        `json:"session_id"`
	SourceUpdatedAt                  int64         `json:"source_updated_at"`
	RawMemory                        string        `json:"raw_memory"`
	RolloutSummary                   string        `json:"rollout_summary"`
	RolloutSlug                      string        `json:"rollout_slug"`
	RolloutSummaryFile               string        `json:"rollout_summary_file"`
	UsageCount                       int64         `json:"usage_count"`
	LastUsage                        sql.NullInt64 `json:"last_usage"`
	SelectedForPhase2                int64         `json:"selected_for_phase2"`
	SelectedForPhase2SourceUpdatedAt sql.NullInt64 `json:"selected_for_phase2_source_updated_at"`
	GeneratedAt                      int64         `json:"generated_at"`
	UsedAt                           int64         `json:"used_at"`
	UpdatedAt                        int64         `json:"updated_at"`
	CreatedAt                        int64         `json:"created_at"`
}

func (q *Queries) GetPhase2InputSelection(ctx context.Context, updatedAt int64) ([]GetPhase2InputSelectionRow, error) {
	rows, err := q.query(ctx, q.getPhase2InputSelectionStmt, getPhase2InputSelection, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPhase2InputSelectionRow{}
	for rows.Next() {
		var i GetPhase2InputSelectionRow
		if err := rows.Scan(
			&i.SessionID,
			&i.SourceUpdatedAt,
			&i.RawMemory,
			&i.RolloutSummary,
			&i.RolloutSlug,
			&i.RolloutSummaryFile,
			&i.UsageCount,
			&i.LastUsage,
			&i.SelectedForPhase2,
			&i.SelectedForPhase2SourceUpdatedAt,
			&i.GeneratedAt,
			&i.UsedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStage1OutputBySessionID = `-- name: GetStage1OutputBySessionID :one
SELECT session_id, source_updated_at, raw_memory, rollout_summary, rollout_slug, rollout_summary_file, usage_count, last_usage, selected_for_phase2, selected_for_phase2_source_updated_at, generated_at, used_at, updated_at, created_at
FROM memory_stage1_outputs
WHERE session_id = ?
`

type GetStage1OutputBySessionIDRow struct {
	SessionID                        string        `json:"session_id"`
	SourceUpdatedAt                  int64         `json:"source_updated_at"`
	RawMemory                        string        `json:"raw_memory"`
	RolloutSummary                   string        `json:"rollout_summary"`
	RolloutSlug                      string        `json:"rollout_slug"`
	RolloutSummaryFile               string        `json:"rollout_summary_file"`
	UsageCount                       int64         `json:"usage_count"`
	LastUsage                        sql.NullInt64 `json:"last_usage"`
	SelectedForPhase2                int64         `json:"selected_for_phase2"`
	SelectedForPhase2SourceUpdatedAt sql.NullInt64 `json:"selected_for_phase2_source_updated_at"`
	GeneratedAt                      int64         `json:"generated_at"`
	UsedAt                           int64         `json:"used_at"`
	UpdatedAt                        int64         `json:"updated_at"`
	CreatedAt                        int64         `json:"created_at"`
}

func (q *Queries) GetStage1OutputBySessionID(ctx context.Context, sessionID string) (GetStage1OutputBySessionIDRow, error) {
	row := q.queryRow(ctx, q.getStage1OutputBySessionIDStmt, getStage1OutputBySessionID, sessionID)
	var i GetStage1OutputBySessionIDRow
	err := row.Scan(
		&i.SessionID,
		&i.SourceUpdatedAt,
		&i.RawMemory,
		&i.RolloutSummary,
		&i.RolloutSlug,
		&i.RolloutSummaryFile,
		&i.UsageCount,
		&i.LastUsage,
		&i.SelectedForPhase2,
		&i.SelectedForPhase2SourceUpdatedAt,
		&i.GeneratedAt,
		&i.UsedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const heartbeatGlobalPhase2Job = `-- name: HeartbeatGlobalPhase2Job :execrows
UPDATE memory_phase2_jobs
SET lease_expires_at = ?,
    updated_at = unixepoch()
WHERE singleton_id = 1
  AND claim_token = ?
`

type HeartbeatGlobalPhase2JobParams struct {
	LeaseExpiresAt sql.NullInt64  `json:"lease_expires_at"`
	ClaimToken     sql.NullString `json:"claim_token"`
}

func (q *Queries) HeartbeatGlobalPhase2Job(ctx context.Context, arg HeartbeatGlobalPhase2JobParams) (int64, error) {
	result, err := q.exec(ctx, q.heartbeatGlobalPhase2JobStmt, heartbeatGlobalPhase2Job, arg.LeaseExpiresAt, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertMemoryRegistryCitation = `-- name: InsertMemoryRegistryCitation :exec
INSERT INTO memory_registry_citations (
    registry_entry_id,
    session_id,
    citation_type,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    unixepoch()
)
`

type InsertMemoryRegistryCitationParams struct {
	RegistryEntryID string `json:"registry_entry_id"`
	SessionID       string `json:"session_id"`
	CitationType    string `json:"citation_type"`
}

func (q *Queries) InsertMemoryRegistryCitation(ctx context.Context, arg InsertMemoryRegistryCitationParams) error {
	_, err := q.exec(ctx, q.insertMemoryRegistryCitationStmt, insertMemoryRegistryCitation, arg.RegistryEntryID, arg.SessionID, arg.CitationType)
	return err
}

const listEligibleStage1OutputsForPhase2 = `-- name: ListEligibleStage1OutputsForPhase2 :many
SELECT session_id, source_updated_at, raw_memory, rollout_summary, rollout_slug, rollout_summary_file, usage_count, last_usage, selected_for_phase2, selected_for_phase2_source_updated_at, generated_at, used_at, updated_at, created_at
FROM memory_stage1_outputs
WHERE (length(trim(raw_memory)) > 0 OR length(trim(rollout_summary)) > 0)
  AND (
        (last_usage IS NOT NULL AND last_usage >= ?1)
        OR (last_usage IS NULL AND source_updated_at >= ?1)
  )
ORDER BY usage_count DESC, COALESCE(last_usage, source_updated_at) DESC, source_updated_at DESC, session_id DESC
LIMIT ?2
`

type ListEligibleStage1OutputsForPhase2Params struct {
	Cutoff     sql.NullInt64 `json:"cutoff"`
	LimitCount int64         `json:"limit_count"`
}

type ListEligibleStage1OutputsForPhase2Row struct {
	SessionID                        string        `json:"session_id"`
	SourceUpdatedAt                  int64         `json:"source_updated_at"`
	RawMemory                        string        `json:"raw_memory"`
	RolloutSummary                   string        `json:"rollout_summary"`
	RolloutSlug                      string        `json:"rollout_slug"`
	RolloutSummaryFile               string        `json:"rollout_summary_file"`
	UsageCount                       int64         `json:"usage_count"`
	LastUsage                        sql.NullInt64 `json:"last_usage"`
	SelectedForPhase2                int64         `json:"selected_for_phase2"`
	SelectedForPhase2SourceUpdatedAt sql.NullInt64 `json:"selected_for_phase2_source_updated_at"`
	GeneratedAt                      int64         `json:"generated_at"`
	UsedAt                           int64         `json:"used_at"`
	UpdatedAt                        int64         `json:"updated_at"`
	CreatedAt                        int64         `json:"created_at"`
}

func (q *Queries) ListEligibleStage1OutputsForPhase2(ctx context.Context, arg ListEligibleStage1OutputsForPhase2Params) ([]ListEligibleStage1OutputsForPhase2Row, error) {
	rows, err := q.query(ctx, q.listEligibleStage1OutputsForPhase2Stmt, listEligibleStage1OutputsForPhase2, arg.Cutoff, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligibleStage1OutputsForPhase2Row{}
	for rows.Next() {
		var i ListEligibleStage1OutputsForPhase2Row
		if err := rows.Scan(
			&i.SessionID,
			&i.SourceUpdatedAt,
			&i.RawMemory,
			&i.RolloutSummary,
			&i.RolloutSlug,
			&i.RolloutSummaryFile,
			&i.UsageCount,
			&i.LastUsage,
			&i.SelectedForPhase2,
			&i.SelectedForPhase2SourceUpdatedAt,
			&i.GeneratedAt,
			&i.UsedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryMaterializations = `-- name: ListMemoryMaterializations :many
SELECT path, kind, content, session_id, updated_at, created_at
FROM memory_materializations
ORDER BY path ASC
`

func (q *Queries) ListMemoryMaterializations(ctx context.Context) ([]MemoryMaterialization, error) {
	rows, err := q.query(ctx, q.listMemoryMaterializationsStmt, listMemoryMaterializations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryMaterialization{}
	for rows.Next() {
		var i MemoryMaterialization
		if err := rows.Scan(
			&i.Path,
			&i.Kind,
			&i.Content,
			&i.SessionID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryRegistryCitationsByEntry = `-- name: ListMemoryRegistryCitationsByEntry :many
SELECT registry_entry_id, session_id, citation_type, created_at
FROM memory_registry_citations
WHERE registry_entry_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMemoryRegistryCitationsByEntry(ctx context.Context, registryEntryID string) ([]MemoryRegistryCitation, error) {
	rows, err := q.query(ctx, q.listMemoryRegistryCitationsByEntryStmt, listMemoryRegistryCitationsByEntry, registryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryRegistryCitation{}
	for rows.Next() {
		var i MemoryRegistryCitation
		if err := rows.Scan(
			&i.RegistryEntryID,
			&i.SessionID,
			&i.CitationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryRegistryEntries = `-- name: ListMemoryRegistryEntries :many
SELECT id, canonical_key, kind, title, body, source_session_id, rollout_summary_file, stale, updated_at, created_at
FROM memory_registry_entries
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListMemoryRegistryEntries(ctx context.Context) ([]MemoryRegistryEntry, error) {
	rows, err := q.query(ctx, q.listMemoryRegistryEntriesStmt, listMemoryRegistryEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryRegistryEntry{}
	for rows.Next() {
		var i MemoryRegistryEntry
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalKey,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.SourceSessionID,
			&i.RolloutSummaryFile,
			&i.Stale,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhase2BaselineOutputs = `-- name: ListPhase2BaselineOutputs :many
SELECT session_id, source_updated_at, raw_memory, rollout_summary, rollout_slug, rollout_summary_file, usage_count, last_usage, selected_for_phase2, selected_for_phase2_source_updated_at, generated_at, used_at, updated_at, created_at
FROM memory_stage1_outputs
WHERE selected_for_phase2 = 1
ORDER BY source_updated_at DESC, session_id DESC
`

type ListPhase2BaselineOutputsRow struct {
	SessionID                        string        `json:"session_id"`
	SourceUpdatedAt                  int64         `json:"source_updated_at"`
	RawMemory                        string        `json:"raw_memory"`
	RolloutSummary                   string        `json:"rollout_summary"`
	RolloutSlug                      string        `json:"rollout_slug"`
	RolloutSummaryFile               string        `json:"rollout_summary_file"`
	UsageCount                       int64         `json:"usage_count"`
	LastUsage                        sql.NullInt64 `json:"last_usage"`
	SelectedForPhase2                int64         `json:"selected_for_phase2"`
	SelectedForPhase2SourceUpdatedAt sql.NullInt64 `json:"selected_for_phase2_source_updated_at"`
	GeneratedAt                      int64         `json:"generated_at"`
	UsedAt                           int64         `json:"used_at"`
	UpdatedAt                        int64         `json:"updated_at"`
	CreatedAt                        int64         `json:"created_at"`
}

func (q *Queries) ListPhase2BaselineOutputs(ctx context.Context) ([]ListPhase2BaselineOutputsRow, error) {
	rows, err := q.query(ctx, q.listPhase2BaselineOutputsStmt, listPhase2BaselineOutputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhase2BaselineOutputsRow{}
	for rows.Next() {
		var i ListPhase2BaselineOutputsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.SourceUpdatedAt,
			&i.RawMemory,
			&i.RolloutSummary,
			&i.RolloutSlug,
			&i.RolloutSummaryFile,
			&i.UsageCount,
			&i.LastUsage,
			&i.SelectedForPhase2,
			&i.SelectedForPhase2SourceUpdatedAt,
			&i.GeneratedAt,
			&i.UsedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStage1OutputsForPhase2 = `-- name: ListStage1OutputsForPhase2 :many
SELECT session_id, source_updated_at, raw_memory, rollout_summary, rollout_slug, rollout_summary_file, usage_count, last_usage, selected_for_phase2, selected_for_phase2_source_updated_at, generated_at, used_at, updated_at, created_at
FROM memory_stage1_outputs
ORDER BY source_updated_at DESC, session_id DESC
`

type ListStage1OutputsForPhase2Row struct {
	SessionID                        string        `json:"session_id"`
	SourceUpdatedAt                  int64         `json:"source_updated_at"`
	RawMemory                        string        `json:"raw_memory"`
	RolloutSummary                   string        `json:"rollout_summary"`
	RolloutSlug                      string        `json:"rollout_slug"`
	RolloutSummaryFile               string        `json:"rollout_summary_file"`
	UsageCount                       int64         `json:"usage_count"`
	LastUsage                        sql.NullInt64 `json:"last_usage"`
	SelectedForPhase2                int64         `json:"selected_for_phase2"`
	SelectedForPhase2SourceUpdatedAt sql.NullInt64 `json:"selected_for_phase2_source_updated_at"`
	GeneratedAt                      int64         `json:"generated_at"`
	UsedAt                           int64         `json:"used_at"`
	UpdatedAt                        int64         `json:"updated_at"`
	CreatedAt                        int64         `json:"created_at"`
}

func (q *Queries) ListStage1OutputsForPhase2(ctx context.Context) ([]ListStage1OutputsForPhase2Row, error) {
	rows, err := q.query(ctx, q.listStage1OutputsForPhase2Stmt, listStage1OutputsForPhase2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStage1OutputsForPhase2Row{}
	for rows.Next() {
		var i ListStage1OutputsForPhase2Row
		if err := rows.Scan(
			&i.SessionID,
			&i.SourceUpdatedAt,
			&i.RawMemory,
			&i.RolloutSummary,
			&i.RolloutSlug,
			&i.RolloutSummaryFile,
			&i.UsageCount,
			&i.LastUsage,
			&i.SelectedForPhase2,
			&i.SelectedForPhase2SourceUpdatedAt,
			&i.GeneratedAt,
			&i.UsedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPhase2Dirty = `-- name: MarkPhase2Dirty :exec
UPDATE memory_phase2_jobs
SET dirty = 1,
    input_watermark = CASE
        WHEN input_watermark >= unixepoch() THEN input_watermark + 1
        ELSE unixepoch()
    END,
    updated_at = unixepoch()
WHERE singleton_id = 1
`

func (q *Queries) MarkPhase2Dirty(ctx context.Context) error {
	_, err := q.exec(ctx, q.markPhase2DirtyStmt, markPhase2Dirty)
	return err
}

const markStage1JobFailed = `-- name: MarkStage1JobFailed :exec
UPDATE memory_stage1_jobs
SET status = 'failed',
    claimed_by = NULL,
    lease_expires_at = NULL,
    retry_after = ?,
    updated_at = unixepoch()
WHERE session_id = ?
`

type MarkStage1JobFailedParams struct {
	RetryAfter int64  `json:"retry_after"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) MarkStage1JobFailed(ctx context.Context, arg MarkStage1JobFailedParams) error {
	_, err := q.exec(ctx, q.markStage1JobFailedStmt, markStage1JobFailed, arg.RetryAfter, arg.SessionID)
	return err
}

const markStage1JobNoOutput = `-- name: MarkStage1JobNoOutput :exec
UPDATE memory_stage1_jobs
SET status = 'succeeded_no_output',
    claimed_by = NULL,
    lease_expires_at = NULL,
    retry_after = 0,
    updated_at = unixepoch()
WHERE session_id = ?
`

func (q *Queries) MarkStage1JobNoOutput(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.markStage1JobNoOutputStmt, markStage1JobNoOutput, sessionID)
	return err
}

const markStage1JobSucceeded = `-- name: MarkStage1JobSucceeded :exec
UPDATE memory_stage1_jobs
SET status = 'succeeded_with_output',
    claimed_by = NULL,
    lease_expires_at = NULL,
    retry_after = 0,
    updated_at = unixepoch()
WHERE session_id = ?
`

func (q *Queries) MarkStage1JobSucceeded(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.markStage1JobSucceededStmt, markStage1JobSucceeded, sessionID)
	return err
}

const markStage1OutputSelectedForPhase2 = `-- name: MarkStage1OutputSelectedForPhase2 :execrows
UPDATE memory_stage1_outputs
SET selected_for_phase2 = 1,
    selected_for_phase2_source_updated_at = source_updated_at
WHERE session_id = ?
  AND source_updated_at = ?
`

type MarkStage1OutputSelectedForPhase2Params struct {
	SessionID       string `json:"session_id"`
	SourceUpdatedAt int64  `json:"source_updated_at"`
}

func (q *Queries) MarkStage1OutputSelectedForPhase2(ctx context.Context, arg MarkStage1OutputSelectedForPhase2Params) (int64, error) {
	result, err := q.exec(ctx, q.markStage1OutputSelectedForPhase2Stmt, markStage1OutputSelectedForPhase2, arg.SessionID, arg.SourceUpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneStage1OutputsForRetention = `-- name: PruneStage1OutputsForRetention :execrows
DELETE FROM memory_stage1_outputs
WHERE session_id IN (
    SELECT o.session_id
    FROM memory_stage1_outputs AS o
    WHERE o.selected_for_phase2 = 0
      AND COALESCE(o.last_usage, o.source_updated_at) < ?
    ORDER BY COALESCE(o.last_usage, o.source_updated_at) ASC, o.source_updated_at ASC, o.session_id ASC
    LIMIT ?
)
`

type PruneStage1OutputsForRetentionParams struct {
	LastUsage sql.NullInt64 `json:"last_usage"`
	Limit     int64         `json:"limit"`
}

func (q *Queries) PruneStage1OutputsForRetention(ctx context.Context, arg PruneStage1OutputsForRetentionParams) (int64, error) {
	result, err := q.exec(ctx, q.pruneStage1OutputsForRetentionStmt, pruneStage1OutputsForRetention, arg.LastUsage, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordStage1OutputUsage = `-- name: RecordStage1OutputUsage :exec
UPDATE memory_stage1_outputs
SET usage_count = usage_count + 1,
    last_usage = unixepoch()
WHERE session_id = ?
`

func (q *Queries) RecordStage1OutputUsage(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.recordStage1OutputUsageStmt, recordStage1OutputUsage, sessionID)
	return err
}

const replaceMemoryRegistryCitations = `-- name: ReplaceMemoryRegistryCitations :exec
DELETE FROM memory_registry_citations
WHERE registry_entry_id = ?
`

func (q *Queries) ReplaceMemoryRegistryCitations(ctx context.Context, registryEntryID string) error {
	_, err := q.exec(ctx, q.replaceMemoryRegistryCitationsStmt, replaceMemoryRegistryCitations, registryEntryID)
	return err
}

const succeedGlobalPhase2Job = `-- name: SucceedGlobalPhase2Job :execrows
UPDATE memory_phase2_jobs
SET status = 'idle',
    claim_token = NULL,
    lease_expires_at = NULL,
    retry_after = 0,
    input_watermark = CASE
        WHEN input_watermark > ? THEN input_watermark
        ELSE ?
    END,
    last_output_watermark = CASE
        WHEN last_output_watermark > ? THEN last_output_watermark
        ELSE ?
    END,
    last_error = '',
    updated_at = unixepoch()
WHERE singleton_id = 1
  AND claim_token = ?
`

type SucceedGlobalPhase2JobParams struct {
	InputWatermark        int64          `json:"input_watermark"`
	InputWatermark_2      int64          `json:"input_watermark_2"`
	LastOutputWatermark   int64          `json:"last_output_watermark"`
	LastOutputWatermark_2 int64          `json:"last_output_watermark_2"`
	ClaimToken            sql.NullString `json:"claim_token"`
}

func (q *Queries) SucceedGlobalPhase2Job(ctx context.Context, arg SucceedGlobalPhase2JobParams) (int64, error) {
	result, err := q.exec(ctx, q.succeedGlobalPhase2JobStmt, succeedGlobalPhase2Job,
		arg.InputWatermark,
		arg.InputWatermark_2,
		arg.LastOutputWatermark,
		arg.LastOutputWatermark_2,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMemoryMaterialization = `-- name: UpsertMemoryMaterialization :one
INSERT INTO memory_materializations (
    path,
    kind,
    content,
    session_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    unixepoch(),
    unixepoch()
)
ON CONFLICT(path) DO UPDATE SET
    kind = excluded.kind,
    content = excluded.content,
    session_id = excluded.session_id,
    updated_at = unixepoch()
RETURNING path, kind, content, session_id, updated_at, created_at
`

type UpsertMemoryMaterializationParams struct {
	Path      string         `json:"path"`
	Kind      string         `json:"kind"`
	Content   string         `json:"content"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) UpsertMemoryMaterialization(ctx context.Context, arg UpsertMemoryMaterializationParams) (MemoryMaterialization, error) {
	row := q.queryRow(ctx, q.upsertMemoryMaterializationStmt, upsertMemoryMaterialization,
		arg.Path,
		arg.Kind,
		arg.Content,
		arg.SessionID,
	)
	var i MemoryMaterialization
	err := row.Scan(
		&i.Path,
		&i.Kind,
		&i.Content,
		&i.SessionID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMemoryRegistryEntry = `-- name: UpsertMemoryRegistryEntry :one
INSERT INTO memory_registry_entries (
    id,
    canonical_key,
    kind,
    title,
    body,
    source_session_id,
    rollout_summary_file,
    stale,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    unixepoch(),
    unixepoch()
)
ON CONFLICT(canonical_key) DO UPDATE SET
    kind = excluded.kind,
    title = excluded.title,
    body = excluded.body,
    source_session_id = excluded.source_session_id,
    rollout_summary_file = excluded.rollout_summary_file,
    stale = excluded.stale,
    updated_at = unixepoch()
RETURNING id, canonical_key, kind, title, body, source_session_id, rollout_summary_file, stale, updated_at, created_at
`

type UpsertMemoryRegistryEntryParams struct {
	ID                 string         `json:"id"`
	CanonicalKey       string         `json:"canonical_key"`
	Kind               string         `json:"kind"`
	Title              string         `json:"title"`
	Body               string         `json:"body"`
	SourceSessionID    sql.NullString `json:"source_session_id"`
	RolloutSummaryFile string         `json:"rollout_summary_file"`
	Stale              int64          `json:"stale"`
}

func (q *Queries) UpsertMemoryRegistryEntry(ctx context.Context, arg UpsertMemoryRegistryEntryParams) (MemoryRegistryEntry, error) {
	row := q.queryRow(ctx, q.upsertMemoryRegistryEntryStmt, upsertMemoryRegistryEntry,
		arg.ID,
		arg.CanonicalKey,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.SourceSessionID,
		arg.RolloutSummaryFile,
		arg.Stale,
	)
	var i MemoryRegistryEntry
	err := row.Scan(
		&i.ID,
		&i.CanonicalKey,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.SourceSessionID,
		&i.RolloutSummaryFile,
		&i.Stale,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertStage1Output = `-- name: UpsertStage1Output :exec
INSERT INTO memory_stage1_outputs (
    session_id,
    source_updated_at,
    raw_memory,
    rollout_summary,
    rollout_slug,
    rollout_summary_file,
    last_usage,
    generated_at,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    NULL,
    unixepoch(),
    unixepoch(),
    unixepoch()
)
ON CONFLICT(session_id) DO UPDATE SET
    source_updated_at = excluded.source_updated_at,
    raw_memory = excluded.raw_memory,
    rollout_summary = excluded.rollout_summary,
    rollout_slug = excluded.rollout_slug,
    rollout_summary_file = excluded.rollout_summary_file,
    generated_at = unixepoch(),
    updated_at = unixepoch()
`

type UpsertStage1OutputParams struct {
	SessionID          string `json:"session_id"`
	SourceUpdatedAt    int64  `json:"source_updated_at"`
	RawMemory          string `json:"raw_memory"`
	RolloutSummary     string `json:"rollout_summary"`
	RolloutSlug        string `json:"rollout_slug"`
	RolloutSummaryFile string `json:"rollout_summary_file"`
}

func (q *Queries) UpsertStage1Output(ctx context.Context, arg UpsertStage1OutputParams) error {
	_, err := q.exec(ctx, q.upsertStage1OutputStmt, upsertStage1Output,
		arg.SessionID,
		arg.SourceUpdatedAt,
		arg.RawMemory,
		arg.RolloutSummary,
		arg.RolloutSlug,
		arg.RolloutSummaryFile,
	)
	return err
}
