// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tiered_memory.sql

package db

import (
	"context"
	"database/sql"
)

const createStructuredSummary = `-- name: CreateStructuredSummary :one
INSERT INTO structured_summaries (id, session_id, summary_data, updated_at, created_at)
VALUES (?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, session_id, summary_data, updated_at, created_at
`

type CreateStructuredSummaryParams struct {
	ID          string `json:"id"`
	SessionID   string `json:"session_id"`
	SummaryData string `json:"summary_data"`
}

func (q *Queries) CreateStructuredSummary(ctx context.Context, arg CreateStructuredSummaryParams) (StructuredSummary, error) {
	row := q.queryRow(ctx, q.createStructuredSummaryStmt, createStructuredSummary, arg.ID, arg.SessionID, arg.SummaryData)
	var i StructuredSummary
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SummaryData,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCodebaseKnowledgeByFilePath = `-- name: GetCodebaseKnowledgeByFilePath :many
SELECT id, file_path, symbol_name, symbol_type, signature, documentation, location_range, updated_at, created_at FROM codebase_knowledge WHERE file_path = ?
`

func (q *Queries) GetCodebaseKnowledgeByFilePath(ctx context.Context, filePath string) ([]CodebaseKnowledge, error) {
	rows, err := q.query(ctx, q.getCodebaseKnowledgeByFilePathStmt, getCodebaseKnowledgeByFilePath, filePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodebaseKnowledge{}
	for rows.Next() {
		var i CodebaseKnowledge
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.SymbolName,
			&i.SymbolType,
			&i.Signature,
			&i.Documentation,
			&i.LocationRange,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectConstitution = `-- name: GetProjectConstitution :one
SELECT id, content, updated_at, created_at FROM project_constitution WHERE id = ? LIMIT 1
`

func (q *Queries) GetProjectConstitution(ctx context.Context, id string) (ProjectConstitution, error) {
	row := q.queryRow(ctx, q.getProjectConstitutionStmt, getProjectConstitution, id)
	var i ProjectConstitution
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStructuredSummaryBySessionID = `-- name: GetStructuredSummaryBySessionID :one
SELECT id, session_id, summary_data, updated_at, created_at FROM structured_summaries WHERE session_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetStructuredSummaryBySessionID(ctx context.Context, sessionID string) (StructuredSummary, error) {
	row := q.queryRow(ctx, q.getStructuredSummaryBySessionIDStmt, getStructuredSummaryBySessionID, sessionID)
	var i StructuredSummary
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SummaryData,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCodebaseKnowledge = `-- name: UpsertCodebaseKnowledge :one
INSERT INTO codebase_knowledge (
    id, file_path, symbol_name, symbol_type, signature, documentation, location_range, updated_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
ON CONFLICT(file_path, symbol_name, symbol_type) DO UPDATE SET
    signature = excluded.signature,
    documentation = excluded.documentation,
    location_range = excluded.location_range,
    updated_at = strftime('%s', 'now')
RETURNING id, file_path, symbol_name, symbol_type, signature, documentation, location_range, updated_at, created_at
`

type UpsertCodebaseKnowledgeParams struct {
	ID            string         `json:"id"`
	FilePath      string         `json:"file_path"`
	SymbolName    string         `json:"symbol_name"`
	SymbolType    string         `json:"symbol_type"`
	Signature     sql.NullString `json:"signature"`
	Documentation sql.NullString `json:"documentation"`
	LocationRange sql.NullString `json:"location_range"`
}

func (q *Queries) UpsertCodebaseKnowledge(ctx context.Context, arg UpsertCodebaseKnowledgeParams) (CodebaseKnowledge, error) {
	row := q.queryRow(ctx, q.upsertCodebaseKnowledgeStmt, upsertCodebaseKnowledge,
		arg.ID,
		arg.FilePath,
		arg.SymbolName,
		arg.SymbolType,
		arg.Signature,
		arg.Documentation,
		arg.LocationRange,
	)
	var i CodebaseKnowledge
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.SymbolName,
		&i.SymbolType,
		&i.Signature,
		&i.Documentation,
		&i.LocationRange,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertProjectConstitution = `-- name: UpsertProjectConstitution :one
INSERT INTO project_constitution (id, content, updated_at, created_at)
VALUES (?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
ON CONFLICT(id) DO UPDATE SET
    content = excluded.content,
    updated_at = strftime('%s', 'now')
RETURNING id, content, updated_at, created_at
`

type UpsertProjectConstitutionParams struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpsertProjectConstitution(ctx context.Context, arg UpsertProjectConstitutionParams) (ProjectConstitution, error) {
	row := q.queryRow(ctx, q.upsertProjectConstitutionStmt, upsertProjectConstitution, arg.ID, arg.Content)
	var i ProjectConstitution
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
